### ISSUE TITLE
Allow specifying directory where terraform will run in

### ISSUE THREAD

**Issue by ulich** [rundeck/serverless-terraform-outputs#4]
We would like to place our terraform infrastructure resource definitions inside the same project, but into a subfolder, so the main folder isn't that cluttered with all kinds of different files.

Maybe like this?

```
${terraform:workspace:directory:variablepath}
```

Or alternatively with a global variable?

**Comment by ProTip** [comment]
This is a really good idea. We are actually using this in a multi-project context, so this would save copying the slim `main.tf` into each serverless project.

It might make sense to be able to setup directory aliases in the config, and then use those in the variable substitution..
